name: 'set-env'
description: 'Prepare variables and outputs'
inputs:
  registryUrl:
    description: 'Container registry url'
    required: true
  appNameSuffix:
    description: String that will be appended to the image name (useful if you have more than one image per repo)
    required: false
    default: ''
outputs:
  appName:
    description: 'Computer-friendly app name'
    value: ${{ steps.prep.outputs.appName }}
  appRegistryUrl:
    description: 'Registry URL, complete with app name and commit SHA'
    value: ${{ steps.prep.outputs.appRegistryUrl }}

runs:
  using: 'composite'
  steps:
    - id: prep
      run: |
        APP_NAME=$(echo $GITHUB_REPOSITORY | sed -e 's/.*\///g' | tr '[:upper:]' '[:lower:]')
        if [ -n "${{ inputs.appNameSuffix }}" ]; then
          APP_NAME="${APP_NAME}-${{ inputs.appNameSuffix }}"
        fi

        APP_REGISTRY_URL="${{ inputs.registryUrl }}/${APP_NAME}:${GITHUB_SHA}"
        echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
        echo "APP_REGISTRY_URL=$APP_REGISTRY_URL" >> $GITHUB_ENV
        echo ::set-output name=appName::"$(echo $APP_NAME)"
        echo ::set-output name=appRegistryUrl::"$(echo $APP_REGISTRY_URL)"
      shell: bash
