# action.yml
name: 'docker'
description: 'Build and push the docker image'
inputs:
  appRegistryUrl:
    description: 'Registry URL, complete with app name and commit SHA'
    required: true
  dockerContext:
    description: 'Context path that will be passed to the `docker build` command'
    required: false
    default: '.'
  nodeAuthToken:
    description: 'NPM Auth token to install with'
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        function runHook() {
          if [ -n "$1" ]; then
            eval "$1"
          fi
        }

        runHook "$DOCKER_BUILD_BEFORE"
        docker build -t ${{ inputs.appRegistryUrl }} ${{ inputs.dockerContext }} --build-arg NODE_AUTH_TOKEN="${{ inputs.nodeAuthToken }}"
        runHook "$DOCKER_BUILD_AFTER"

        runHook "$DOCKER_PUSH_BEFORE"
        docker push ${{ inputs.appRegistryUrl }}
        runHook "$DOCKER_PUSH_AFTER"
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.nodeAuthToken }}
