# action.yml
name: 'argo-push'
description: 'Push the updated ArgoCD state'
inputs:
  stateRepoDir:
    description: 'Path to the cloned ArgoCD state repository'
    required: true
outputs:
  prBranch:
    description: 'Generated branch name in the ArgoCD state repository'
    value: ${{ steps.push.outputs.prBranch }}

runs:
  using: 'composite'
  steps:
    - id: push
      run: |
        GIT_PR_BRANCH="${GITHUB_ACTOR}__${APP_NAME}__${GITHUB_SHA}"
        cd ${{ inputs.stateRepoDir }}
        git checkout -b ${GIT_PR_BRANCH}
        git add ${{ inputs.stateRepoDir }}/${APP_NAME}/${APP_NAME}.yml
        git commit -m "${APP_NAME} pushed ${GITHUB_SHA}"
        git push --set-upstream origin ${GIT_PR_BRANCH}
        echo "::set-output name=prBranch::${GIT_PR_BRANCH}"
      shell: bash
